DROP TABLE IF EXISTS USER_ORIGIN;
CREATE TABLE USER_ORIGIN
(
    id           BIGINT AUTO_INCREMENT,
    user_name    VARCHAR(255) NOT NULL UNIQUE,
    password     VARCHAR(255),
    email        VARCHAR(255) UNIQUE,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status       VARCHAR(50) DEFAULT 'ACTIVE',
    deleted_at   TIMESTAMP NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS USER_OAUTH;
CREATE TABLE USER_OAUTH
(
    id           BIGINT AUTO_INCREMENT,
    user_id      BIGINT FOREIGN KEY REFERENCES USER_ORIGIN(id),
    provider     VARCHAR(100) NOT NULL,
    provider_id  VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMP NULL,
    UNIQUE (provider, provider_id),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS USER_HISTORY;
CREATE TABLE USER_HISTORY
(
    id           BIGINT AUTO_INCREMENT,
    user_id      BIGINT FOREIGN KEY REFERENCES USER_ORIGIN(id),
    action       VARCHAR(255) NOT NULL,
    action_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details      TEXT,
    PRIMARY KEY (id)
);