package com.sangsang.autoblog.domain.model;

import java.util.Date;

import lombok.Getter;

@Getter
public class AutoContent {
    private String title;
    private String body;
    private String[] tags;
    private String imageUrl;
    private String summary;
    private Date date;

    public AutoContent(){
        this.title = "[Generated Title] How to build a blog with AI";
        this.body = "[Generated Body] This is a sample blog post generated by AI...";
        this.tags = new String[]{"AI", "Blogging", "Technology"};
        this.imageUrl = "https://example.com/sample-image.jpg";
        this.summary = "[Generated Summary] A brief overview of building a blog using AI technologies.";
        this.date = new Date();
    }

    public AutoContent(String title, String body, String[] tags, String imageUrl, String summary, Date date) {
        if(title == null || body == null) {
            throw new IllegalArgumentException("Content fields cannot be null");
        }
        this.title = title;
        this.body = body;
        this.tags = tags;
        this.imageUrl = imageUrl;
        this.summary = summary;
        this.date = date;
    }
}
