package com.sangsang.autoblog.domain.model;

import java.time.LocalDateTime;

public class PostContent {
    
    public final String title;
    public final String body;
    public final String[] tags;
    public final String imageUrl;
    public final String summary;
    public final LocalDateTime date;

    public PostContent(){
        this.title = "[Generated Title] How to build a blog with AI";
        this.body = "[Generated Body] This is a sample blog post generated by AI...";
        this.tags = new String[]{"AI", "Blogging", "Technology"};
        this.imageUrl = "https://example.com/sample-image.jpg";
        this.summary = "[Generated Summary] A brief overview of building a blog using AI technologies.";
        this.date = LocalDateTime.now();
    }

    public PostContent(String title, String body, String[] tags, String imageUrl, String summary) {
        if(title == null || body == null) {
            throw new IllegalArgumentException("Content fields cannot be null");
        }
        this.title = title;
        this.body = body;
        this.tags = tags;
        this.imageUrl = imageUrl;
        this.summary = summary;
        this.date = LocalDateTime.now();
    }
}
